title: Linsonjude "Linson" Naval
logo: Television.jpg
description: On regional television channel (NESN) to ask a question to the Red Sox General Manager. I asked him how much decisionmaking on player performance is done with analytics and how much is done with scouting. He deftly deflected.
#show_downloads: true
theme: jekyll-theme-minimal
