title: Linsonjude "Linson" Naval
logo: Television.jpg
#description: <br>
On NESN sports TV to ask a question to the Red Sox General Manager.<br>
https://www.linkedin.com/in/linsonjudenaval/
#show_downloads: true
theme: jekyll-theme-minimal
