title: Linsonjude "Linson" Naval
logo: Television.jpg
description: On NESN sports TV to ask a question to the Red Sox General Manager. https://www.linkedin.com/in/linsonjudenaval/
#show_downloads: true
theme: jekyll-theme-minimal
