title: Linsonjude "Linson" Naval
logo: Television.jpg
description: On NESN sports TV to ask a question to the Red Sox General Manager. 
<a href="https://www.linkedin.com/in/linsonjudenaval/">LinkedIn Profile</a> 
#show_downloads: true
theme: jekyll-theme-minimal
